version: 2
jobs:
  build:
    working_directory: ~/aza-nano-challenges
    docker:
      - image: eosio/eos:v1.5.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: 'apt-get update && apt-get install -yqq git build-essential curl wget && curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -yqq nodejs && wget https://github.com/eosio/eosio.cdt/releases/download/v1.3.2/eosio.cdt-1.3.2.x86_64.deb && apt-get install -yqq ./eosio.cdt-1.3.2.x86_64.deb'
      - run:
          name: update-npm
          command: 'npm i -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run localtest